// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: MyPrompt.flex

package org.oleg.iem.my_prompt_language;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import org.oleg.iem.my_prompt_language.gen.psi.MyPromptTypes;
import com.intellij.psi.TokenType;


class GeneratedMyPromptLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int WAITING_VALUE = 2;
  public static final int WAITING_CELL = 4;
  public static final int WAITING_SEPARATOR = 6;
  public static final int WAITING_CONTEXT_VALUE = 8;
  public static final int WAITING_CONTEXT_SEPARATOR = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  4, 4
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\1\0\1\7\14\0\1\10\12\0\1\11\2\0\1\12"+
    "\1\0\1\13\3\0\1\14\1\15\13\0\1\16\1\17"+
    "\4\0\1\20\12\0\1\21\1\22\2\0\1\23\2\0"+
    "\1\24\1\25\1\0\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\0\1\34\1\35\1\36\1\37\2\0\1\40"+
    "\1\41\2\0\1\42\10\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\43";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\2\2\6\1\1\3\1\1\2\4\1\2"+
    "\1\4\1\1\1\3\1\1\2\2\1\3\1\5\1\6"+
    "\7\0\6\7\12\0\1\4\2\0\1\6\13\0\1\10"+
    "\5\0\1\11\4\0\1\12\10\0\1\13\11\0\1\14"+
    "\3\0\1\15\3\0\1\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\374"+
    "\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01d4\0\u01f8\0\u021c"+
    "\0\u0240\0\330\0\u0264\0\u0264\0\u0288\0\u02ac\0\u02d0\0\u02f4"+
    "\0\u0318\0\u033c\0\264\0\374\0\u0360\0\u0384\0\u03a8\0\u03cc"+
    "\0\u03f0\0\u0414\0\u021c\0\u0438\0\u021c\0\u045c\0\u0264\0\u0240"+
    "\0\u0480\0\u04a4\0\u02d0\0\u04c8\0\u04ec\0\u0510\0\u0534\0\u0558"+
    "\0\u057c\0\u05a0\0\u05c4\0\u05e8\0\u060c\0\u0630\0\u0654\0\u0678"+
    "\0\u069c\0\u06c0\0\u06e4\0\u0708\0\u072c\0\u0750\0\u0774\0\u0798"+
    "\0\u07bc\0\u07e0\0\264\0\u0804\0\u0828\0\u084c\0\u0870\0\u0894"+
    "\0\264\0\u08b8\0\u08dc\0\u0900\0\u0924\0\264\0\u0948\0\u096c"+
    "\0\u0990\0\u09b4\0\u09d8\0\u09fc\0\u0a20\0\u0a44\0\264\0\u0a68"+
    "\0\u0a8c\0\u0ab0\0\u0ad4\0\u0af8\0\u0b1c\0\u0b40\0\u0b64\0\u0b88"+
    "\0\u0b40\0\u0bac\0\u0bd0\0\u0bf4\0\u0c18\0\u0c3c\0\u0144\0\u0c60"+
    "\0\264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\4\7\1\6\1\11\3\6\1\12"+
    "\1\13\1\14\1\15\1\16\21\6\1\17\1\6\1\20"+
    "\1\21\1\22\1\23\1\24\1\23\1\21\1\25\32\20"+
    "\1\26\1\20\1\27\1\30\1\31\3\7\1\30\33\27"+
    "\1\32\2\6\6\7\2\6\2\33\27\6\1\17\2\6"+
    "\6\7\33\6\1\17\1\6\45\0\6\7\36\0\1\7"+
    "\4\34\1\7\45\0\1\35\65\0\1\36\34\0\1\37"+
    "\54\0\1\40\46\0\1\41\25\0\1\42\30\0\1\17"+
    "\35\0\2\43\1\44\3\45\37\43\1\21\1\46\1\47"+
    "\1\50\1\47\1\21\36\43\1\23\1\51\3\47\1\23"+
    "\35\43\7\0\1\52\34\0\2\43\1\44\3\45\1\26"+
    "\35\43\2\53\1\54\3\0\35\53\1\0\1\53\1\30"+
    "\1\31\3\7\1\30\34\53\2\0\6\7\4\0\1\55"+
    "\30\0\2\53\1\54\3\0\1\32\34\53\7\0\1\56"+
    "\66\0\1\57\50\0\1\60\37\0\1\61\34\0\1\62"+
    "\54\0\1\63\11\0\4\44\37\0\1\64\1\46\1\51"+
    "\1\46\1\51\1\64\36\0\1\7\4\51\1\7\44\0"+
    "\1\65\47\0\1\55\42\0\1\66\31\0\2\56\4\67"+
    "\35\56\37\0\1\70\26\0\1\71\52\0\1\72\47\0"+
    "\1\73\34\0\1\74\17\0\2\64\1\7\1\64\1\7"+
    "\1\64\37\0\3\75\1\76\55\0\1\77\26\0\4\67"+
    "\61\0\1\100\45\0\1\101\51\0\1\102\51\0\1\103"+
    "\23\0\1\104\22\0\2\105\1\0\4\105\1\0\36\105"+
    "\1\75\4\105\1\0\34\105\37\0\1\106\44\0\1\107"+
    "\32\0\1\110\52\0\1\111\27\0\1\112\21\0\2\113"+
    "\1\0\4\113\1\0\34\113\23\0\1\114\56\0\1\115"+
    "\42\0\1\116\35\0\1\117\14\0\2\120\1\0\4\120"+
    "\1\0\34\120\34\0\1\121\15\0\1\122\60\0\1\123"+
    "\20\0\2\120\1\124\4\120\1\0\34\120\41\0\1\125"+
    "\16\0\1\126\64\0\1\127\6\0\2\105\1\0\4\105"+
    "\1\130\34\105\42\0\1\131\25\0\1\132\26\0\1\133"+
    "\51\0\1\134\65\0\1\135\13\0\1\136\57\0\1\137"+
    "\51\0\1\140\14\0\4\141\74\0\1\142\33\0\1\143"+
    "\36\0\1\144\57\0\1\145\33\0\1\146\32\0\1\147"+
    "\56\0\1\150\51\0\1\151\6\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3204];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\24\1\1\11\1\1\7\0\6\1\12\0"+
    "\1\1\2\0\1\1\13\0\1\11\5\0\1\11\4\0"+
    "\1\11\10\0\1\11\11\0\1\1\3\0\1\1\3\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  GeneratedMyPromptLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return TokenType.BAD_CHARACTER;
            }
          // fall through
          case 15: break;
          case 2:
            { yybegin(YYINITIAL); return TokenType.WHITE_SPACE;
            }
          // fall through
          case 16: break;
          case 3:
            { yybegin(WAITING_CELL); return MyPromptTypes.PIPE;
            }
          // fall through
          case 17: break;
          case 4:
            { yybegin(WAITING_VALUE); return TokenType.WHITE_SPACE;
            }
          // fall through
          case 18: break;
          case 5:
            { yybegin(WAITING_VALUE); return MyPromptTypes.SEPARATOR;
            }
          // fall through
          case 19: break;
          case 6:
            { yybegin(YYINITIAL); return MyPromptTypes.COMMENT_VALUE;
            }
          // fall through
          case 20: break;
          case 7:
            { yybegin(YYINITIAL); return MyPromptTypes.VALUE_LINE;
            }
          // fall through
          case 21: break;
          case 8:
            { yybegin(WAITING_SEPARATOR); return MyPromptTypes.QUERY_KEYWORD;
            }
          // fall through
          case 22: break;
          case 9:
            { yybegin(WAITING_SEPARATOR); return MyPromptTypes.PROMPT_KEYWORD;
            }
          // fall through
          case 23: break;
          case 10:
            { yybegin(WAITING_SEPARATOR); return MyPromptTypes.DETAILS_KEYWORD;
            }
          // fall through
          case 24: break;
          case 11:
            { yybegin(WAITING_SEPARATOR); return MyPromptTypes.VARIABLES_KEYWORD;
            }
          // fall through
          case 25: break;
          case 12:
            { yybegin(YYINITIAL); return MyPromptTypes.VALUE_MULTILINE;
            }
          // fall through
          case 26: break;
          case 13:
            { yybegin(WAITING_SEPARATOR); return MyPromptTypes.CONTEXT_CHUNKS_KEYWORD;
            }
          // fall through
          case 27: break;
          case 14:
            { yybegin(WAITING_CELL); return MyPromptTypes.VALUE;
            }
          // fall through
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
